services:
  node:
    build: .
    container_name: web_njs
    ports:
      - "3000:3000"
    networks:
      - web_stack
  mysql:
    image: mysql:9.2
    container_name: db_mysql
    env_file: var.env
    ports:
      - 3306:33606
    volumes:
      - ./garageM.sql:/docker-entrypoint-initdb.d/garageM.sql
    networks:
      - web_stack

  php-apache:
    build:
      dockerfile: apache.Dockerfile
    container_name: web_mp
    ports:
      - "93:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - web_stack

networks:
  web_stack:
    name: web_stack
    driver: bridge