version: '3.8'

services:
  web:
    build: .
    image: ruddy/apache:1.0
    ports:
      - "80:80"
    networks:
      - web_stack

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - web_stack

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - web_stack

networks:
  web_stack:
    driver: bridge

volumes:
  pgdata:
