server {
    listen 80;
    server_name tp5.local localhost 127.0.0.1;  # ← virgule manquante corrigée

    location / {
        proxy_pass http://web_app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    access_log /var/log/nginx/supersite_access.log main;
    error_log /var/log/nginx/supersite_error.log;
}