server {
    listen 80;
    server_name tp5.local;
    location / {
        proxy_pass http://web_app:80; # Nom du conteneur cible
        proxy_set_header Host $host;
    }
}
server {
    listen 443;
    server_name tp5.local;
    location / {
        proxy_pass https://web_app:443;
        proxy_set_header Host $host;
    }
}