STOP SLAVE;
CHANGE MASTER TO
  MASTER_HOST='mysql_master',
  MASTER_USER='root',
  MASTER_PASSWORD='mdpRoot23',
  MASTER_PORT=3306,
  MASTER_LOG_FILE='binlog.000002',
  MASTER_LOG_POS=157,
  MASTER_CONNECT_RETRY=10;
START SLAVE;