server {
    listen 80;
    server_name app.little.bloomyindev.me;
    return 301 https://$host$request_uri;
}
 
server {
    listen 443 ssl;
    server_name app.little.bloomyindev.me;
 
    ssl_certificate     /etc/nginx/certs/app.little.bloomyindev.me.crt;
    ssl_certificate_key /etc/nginx/certs/app.little.bloomyindev.me.key;
 
    location / {
        proxy_pass http://web_app:80;
 
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
    }

    location = /mailpit-ui {
        return 301 /mailpit-ui/;
    }

    location /mailpit-ui/ {
        proxy_pass http://mailpit:8025;
        proxy_http_version 1.1;

        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header Upgrade            $http_upgrade;
        proxy_set_header Connection         "upgrade";
    }

    location = /mailpit {
        return 301 /mailpit-ui/;
    }
}